name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: MajorMask/MajorMask
    runs-on: ubuntu-latest
    steps:
      - uses: MajorMask/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_cde9d2d1-7002-45ec-b4a7-6d56b09081ae }}
